### ISSUE TITLE
notify

### ISSUE THREAD

**Issue by Eric-Busch0** [Eric-Busch0/GPS_BOARD#1]
@EdwinFairchild  All of the stuff you need is here

**Comment by EdwinFairchild** [comment]
I need to bring home one of those mini swd ribbon cables what ST programmer are you using? I have the cheap st link v2 and some ST Link V3 Mods which are dope because you can drop them into a design and have onboard debugger.

**Comment by Eric-Busch0** [comment]
> I need to bring home one of those mini swd ribbon cables what ST programmer are you using? I have the cheap st link v2 and some ST Link V3 Mods which are dope because you can drop them into a design and have onboard debugger. 

I'm dumb and used the 10 pin. I had to adapt it with an loomed adapter and some duponts. I ordered some adapter PCBs with the header and some pins for the cheap ST Link. It'll be here probably next week. It'll have both cable options and a header option.
